inventory:
  databaseConfiguration:
    user: ${DB_USER:-root}
    password: ${DB_PASSWORD:-lpsk5713}
    driverClass: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/inventory?allowPublicKeyRetrieval=true&useSSL=false"
    acquireIncrement: 5
    initialPoolSize: 50
    minPoolSize: 10
    maxPoolSize: 100
    maxIdleTime: 840000
    maxStatements: 500
    idleConnectionTestPeriod: 1800000
    connectionTimeout: 5000