inventory:
  databaseConfiguration:
    user: ${DB_USER:-root}
    password: ${DB_PASSWORD:-PasswordDS}
    driverClass: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://${DB_HOST:nomise.ckw6qdo8w9lb.ap-south-1.rds.amazonaws.com}:${DB_PORT:3306}/${DB_NAME:nomise}?useUnicode=yes&characterEncoding=UTF-8&autoReconnect=true&enabledTLSProtocols=TLSv1.2"
    acquireIncrement: 5
    initialPoolSize: 50
    minPoolSize: 10
    maxPoolSize: 100
    maxIdleTime: 840000
    maxStatements: 500
    idleConnectionTestPeriod: 1800000
    connectionTimeout: 500