databaseConfiguration:
  user: ${DB_USER:-root}
  password: ${DB_PASSWORD:-}
  url: "jdbc:mysql://${DB_HOST:-localhost}:${DB_PORT:-3306}"
  acquireIncrement: 5
  initialPoolSize: 50
  minPoolSize: 10
  maxPoolSize: 100
  maxIdleTime: 840000
  maxStatements: 500
  idleConnectionTestPeriod: 1800000
  testStatement: "SELECT 1 FROM DUAL"
  connectionTimeout: 500